server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nodejs-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs-app
          environment: development
          application: monitoring-poc-v2
          log_type: application
          __path__: /var/log/app.log

  - job_name: nodejs-error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs-app
          environment: development
          application: monitoring-poc-v2
          log_type: error
          __path__: /var/log/error.log 